import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { newProject, makeClip, uid, type Media } from '../shared/model';
import { audibleClips, audioSignature, captionWindows, applyCaptions, cuesToSrt, cuesToLrc, type CaptionJob, type CaptionOptions } from '../shared/captions';
import { transcriptCues, extractSpeechAudio, nonSilent } from '../server/speech';
import { Library } from '../server/library';
import { Projects } from '../server/projects';
import { ffmpeg, probe } from '../server/native';

const options:CaptionOptions={mode:'captions',language:'zh',traditional:true,vocalFocus:true};
test('silence detection ignores WAV metadata rather than treating its header as audio',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'mycut-silence-test-'));try{const file=path.join(root,'silence.wav');await ffmpeg(['-f','lavfi','-i','anullsrc=r=16000:cl=mono','-t','1','-c:a','pcm_s16le',file]);assert.equal(await nonSilent(file),false);}finally{await fs.rm(root,{recursive:true,force:true});}});
test('one-hour windows have bounded context and captions keep hour timestamps',()=>{const windows=captionWindows(0,3600);assert.equal(windows.length,120);assert.ok(windows.every(w=>w.to-w.from<=32));assert.equal(windows.at(-1)!.coreTo,3600);const cues=[{id:uid(),text:'一小時之後',start:3600*30+15,duration:60}];assert.match(cuesToSrt(cues,30),/01:00:00,500 --> 01:00:02,500/);assert.equal(cuesToLrc(cues,30),'[60:00.50]一小時之後');});
test('token ownership, traditional Chinese, lyric phrase splitting and special tokens',()=>{const result={transcription:[{text:'测试，歌词。',offsets:{from:0,to:3000},tokens:[{text:'[_BEG_]',offsets:{from:0,to:10}},{text:'测试，',offsets:{from:500,to:1200}},{text:'歌词。',offsets:{from:1500,to:2500}}]}]};const w={from:29,to:61,coreFrom:30,coreTo:60};const cues=transcriptCues(result,w,30,{...options,mode:'lyrics'});assert.equal(cues.length,1);assert.equal(cues[0].text,'歌詞。');assert.equal(cues[0].start,915);const all=transcriptCues(result,{from:0,to:30,coreFrom:0,coreTo:30},30,{...options,mode:'lyrics'});assert.deepEqual(all.map(c=>c.text),['測試，','歌詞。']);});
test('applying captions preserves titles; changing audio prevents stale application',()=>{const p=newProject(),id=uid();const media:Media[]=[{id,name:'audio',kind:'audio',hasAudio:true,width:0,height:0,duration:10,size:100}];p.clips=[makeClip({kind:'audio',mediaId:id,trackId:'voice',start:30,duration:300}),makeClip({kind:'text',trackId:'text',start:0,duration:90,text:'標題'})];const signature=audioSignature(p,media);const job:CaptionJob={id:uid(),projectId:p.id,name:p.name,fps:p.fps,options,signature,status:'completed',stage:'done',progress:1,completedChunks:1,totalChunks:1,duration:10,createdAt:'',cueCount:1};const cues=[{id:uid(),start:35,duration:60,text:'辨識的文字'}];let applied=applyCaptions(p,job,cues,media);assert.equal(applied.clips.length,3);assert.equal(applied.tracks.length,p.tracks.length+1);applied=applyCaptions(applied,job,[{...cues[0],text:'校對過的文字'}],media);assert.equal(applied.clips.length,3);assert.equal(applied.clips.filter(c=>c.text==='標題').length,1);assert.equal(audioSignature({...p,clips:p.clips.map(c=>({...c,fontSize:50}))},media),signature);assert.throws(()=>applyCaptions({...p,clips:p.clips.map(c=>c.kind==='audio'?{...c,speed:2}:c)},job,cues,media),/音訊時間軸已改變/);assert.equal(audibleClips({...p,tracks:p.tracks.map(t=>({...t,muted:true}))},media).length,0);});
test('project rename, duplicate, trash and restore never delete media',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'mycut-projects-test-'));const library=new Library(root);await library.init();const projects=new Projects(root,library);try{const p=newProject();p.name='第一個專案';await projects.save(p);await projects.rename(p.id,'新的名字');assert.equal((await projects.read(p.id)).name,'新的名字');const copy=await projects.duplicate(p.id);assert.notEqual(copy.id,p.id);await projects.move(p.id);assert.equal((await projects.list()).length,1);assert.equal((await projects.list(true))[0].name,'新的名字');await projects.move(p.id,true);assert.equal((await projects.list()).length,2);}finally{library.close();await fs.rm(root,{recursive:true,force:true});}});
test('speech extraction respects clip offset, speed, silence and source selection',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'mycut-audio-test-'));const library=new Library(root);await library.init();try{const file=path.join(root,'source.wav');await ffmpeg(['-f','lavfi','-i','sine=frequency=440:duration=6','-c:a','pcm_s16le',file]);const m=await library.import(file);const p=newProject();const clip=makeClip({kind:'audio',mediaId:m.id,trackId:'voice',start:60,duration:60,sourceIn:1,speed:2});p.clips=[clip];const dest=path.join(root,'chunk.wav');assert.equal(await extractSpeechAudio(p,library,options,0,5,dest),true);const info=await probe(dest);assert.equal(+info.format.duration,5);assert.equal(+info.streams[0].sample_rate,16000);const b=await fs.readFile(dest);const dataOffset=b.indexOf(Buffer.from('data'))+8;const energy=(a:number,z:number)=>{let sum=0;for(let n=Math.round(a*16000);n<z*16000;n++)sum+=Math.abs(b.readInt16LE(dataOffset+n*2));return sum;};assert.equal(energy(0,1.8),0);assert.ok(energy(2.2,3.6)>1000);assert.equal(energy(4.2,4.8),0);assert.equal(await extractSpeechAudio(p,library,{...options,clipId:uid()},0,5,path.join(root,'empty.wav')),false);}finally{library.close();await fs.rm(root,{recursive:true,force:true});}});

test('overlapping recognized cues stay timed on separate lanes; replacements reuse lane budget and honor locks',()=>{const p=newProject(),job:CaptionJob={id:uid(),projectId:p.id,name:p.name,fps:p.fps,options,signature:audioSignature(p,[]),status:'completed',stage:'done',progress:1,completedChunks:1,totalChunks:1,duration:10,createdAt:'',cueCount:2};const cues=[{id:uid(),start:0,duration:90,text:'第一行'},{id:uid(),start:60,duration:90,text:'第二行'}];const result=applyCaptions(p,job,cues,[]);assert.notEqual(result.clips[0].trackId,result.clips[1].trackId);assert.deepEqual(result.clips.map(c=>c.start),[0,60]);const replaced=applyCaptions(result,job,cues,[]);assert.equal(replaced.tracks.length,result.tracks.length);replaced.tracks.find(t=>t.id===replaced.clips[1].trackId)!.locked=true;assert.throws(()=>applyCaptions(replaced,job,cues,[]),/解鎖/);});
