import test from 'node:test';
import assert from 'node:assert/strict';
import { makeClip, newProject, ProjectSchema, uid, evaluateClip, type Media } from '../shared/model';
import { duplicateSelection, expandSelection, moveSelection, patchLinkedClip, removeSelection, setSelectionRelation, splitSelection, trimSelection } from '../shared/editing';
import { applyCaptionBatch, captionOverlaps, wrapCaption } from '../shared/caption-batch';
import { defaultEffects } from '../shared/effects';
import { effectLayersAt, projectNeedsSpectrum, segmentHasEffects } from '../shared/effect-timeline';

function linked(){const p=newProject(),id=uid(),linkId=uid();const video=makeClip({kind:'video',mediaId:id,trackId:'main',start:30,duration:300,sourceIn:2,linkId}),audio=makeClip({...video,id:uid(),kind:'audio',trackId:'music'});p.clips=[video,audio];const media:Media[]=[{id,name:'test.mp4',kind:'video',duration:20,width:1920,height:1080,size:100,hasAudio:true}];return {p,video,audio,media};}
test('connected groups select earlier and later linked members, even from the last clip',()=>{const {p,video,audio}=linked();const groupId=uid();p.clips=[{...video,groupId},audio,makeClip({kind:'text',trackId:'text',start:0,duration:30,groupId})];assert.equal(expandSelection(p,[p.clips[2].id]).length,3);assert.equal(expandSelection(p,[audio.id]).length,3);});
test('linked movement clamps the entire set and locked members block mutations',()=>{const {p,video,audio}=linked();p.clips[1]={...audio,start:45};const moved=moveSelection(p,[video.id],-100);assert.deepEqual(moved.clips.map(c=>c.start),[0,15]);p.tracks.find(t=>t.id==='music')!.locked=true;assert.throws(()=>moveSelection(p,[video.id],10),/鎖定/);assert.throws(()=>duplicateSelection(p,[video.id]),/鎖定/);});
test('linked trim preserves source, karaoke and interpolation; source bounds clamp both tracks',()=>{const {p,video,audio,media}=linked();p.clips=[{...video,keyframes:[{frame:0,x:0,y:0,scale:1,opacity:1},{frame:300,x:1,y:0,scale:2,opacity:0}]},audio];const trimmed=trimSelection(p,[video.id],'left',60,media);assert.deepEqual(trimmed.clips.map(c=>[c.start,c.duration,c.sourceIn,c.karaoke.offset]),[[90,240,4,60],[90,240,4,60]]);assert.equal(evaluateClip(trimmed.clips[0],0).scale,1.2);const longer=trimSelection(p,[audio.id],'right',1000,media);assert.deepEqual(longer.clips.map(c=>c.duration),[540,540]);p.clips[0].keyframes=Array.from({length:300},(_,frame)=>({frame,x:frame/300,y:0,scale:1,opacity:1}));const extended=trimSelection(p,[video.id],'left',-15,media);assert.equal(extended.clips[0].keyframes.length,300);assert.equal(ProjectSchema.safeParse(extended).success,true);assert.equal(evaluateClip(extended.clips[0],0).x,0);assert.equal(ProjectSchema.safeParse(trimSelection(p,[video.id],'left',10,media)).success,true);});
test('duplicate and split keep internal relations but never link back to originals',()=>{const {p,video}=linked();const copied=duplicateSelection(p,[video.id]);assert.equal(copied.project.clips.length,4);assert.equal(copied.project.clips[2].linkId,copied.project.clips[3].linkId);assert.notEqual(copied.project.clips[2].linkId,video.linkId);assert.deepEqual(copied.project.clips.slice(2).map(c=>c.start),[330,330]);const split=splitSelection(p,[video.id],180);assert.equal(split.ids.length,2);const right=split.project.clips.filter(c=>split.ids.includes(c.id));assert.equal(right[0].linkId,right[1].linkId);assert.notEqual(right[0].linkId,video.linkId);assert.deepEqual(right.map(c=>c.sourceIn),[7,7]);assert.equal(removeSelection(p,[video.id]).clips.length,0);});
test('inspector speed and timing edits propagate to linked audio while local properties stay local',()=>{const {p,video,media}=linked();const moved=patchLinkedClip(p,video.id,{start:60,duration:270,opacity:.4},media);assert.deepEqual(moved.clips.map(c=>[c.start,c.duration]),[[60,270],[60,270]]);assert.equal(moved.clips[1].opacity,1);const faster=patchLinkedClip(p,video.id,{speed:2,duration:150},media);assert.deepEqual(faster.clips.map(c=>[c.speed,c.duration]),[[2,150],[2,150]]);});
test('group and link operations are separate; ripple deletion cannot silently break downstream sync',()=>{const {p,video,audio}=linked();const grouped=setSelectionRelation(p,[video.id,audio.id],'groupId',true);assert.equal(grouped.clips[0].groupId,grouped.clips[1].groupId);const ungrouped=setSelectionRelation(grouped,[audio.id],'groupId',false);assert.equal(ungrouped.clips[0].groupId,undefined);assert.equal(ungrouped.clips[0].linkId,video.linkId);const removed=makeClip({kind:'shape',trackId:'main',start:0,duration:30});p.clips.unshift(removed);assert.throws(()=>removeSelection(p,[removed.id],true),/同步/);});
test('old projects retain global effects; timed effects respect fades, keyframes, hiding and exact end boundaries',()=>{const p=newProject();p.tracks.unshift({id:'fx',kind:'effect',name:'特效',hidden:false,locked:false,muted:false});const c=makeClip({kind:'effect',trackId:'fx',start:30,duration:90,effects:{...defaultEffects(),enabled:['spectrum'],intensity:1},fadeIn:30,keyframes:[{frame:0,x:0,y:0,scale:1,opacity:0},{frame:60,x:0,y:0,scale:1,opacity:1}]});p.clips=[c];assert.equal(effectLayersAt(p,29).length,0);assert.equal(effectLayersAt(p,30).length,0);assert.equal(effectLayersAt(p,45)[0].intensity,.125);assert.equal(effectLayersAt(p,60)[0].intensity,.5);assert.equal(effectLayersAt(p,120).length,0);assert.equal(projectNeedsSpectrum(p),true);assert.equal(segmentHasEffects(p,0,30),false);assert.equal(segmentHasEffects(p,30,60),true);assert.deepEqual(ProjectSchema.parse(JSON.parse(JSON.stringify(p))).clips[0].effects,c.effects);p.tracks[0].hidden=true;assert.equal(effectLayersAt(p,90).length,0);assert.equal(projectNeedsSpectrum(p),false);p.effects.enabled=['snow'];assert.deepEqual(effectLayersAt(p,90)[0].enabled,['snow']);assert.equal(ProjectSchema.safeParse({...p,clips:[{...c,trackId:'main'}]}).success,false);});
test('caption batch limits scope, skips locks, replaces literal strings and invalidates word timing only for text changes',()=>{const p=newProject();const a=makeClip({kind:'text',trackId:'text',start:0,duration:90,text:'Hello,世界!',karaoke:{enabled:true,words:[{text:'Hello,世界!',start:0,end:90}],offset:0,color:'#ffffff',source:'manual'}});p.clips=[a,{...a,id:uid(),trackId:'overlay'},{...a,id:uid()}];p.tracks.find(t=>t.id==='overlay')!.locked=true;const edited=applyCaptionBatch(p,[a.id,p.clips[1].id],{find:'Hello',replace:'你好',punctuation:'traditional',lineLength:3});assert.equal(edited.clips[0].text,'你好，\n世界！');assert.equal(edited.clips[0].karaoke.enabled,false);assert.deepEqual(edited.clips[0].karaoke.words,[]);assert.equal(edited.clips[1].text,a.text);assert.equal(edited.clips[2].text,a.text);const styled=applyCaptionBatch(p,[a.id],{find:'',replace:'',punctuation:'keep',lineLength:0,style:{fontId:'huninn',fontSize:70,color:'#aaffaa',textBackground:false}});assert.deepEqual(styled.clips[0].karaoke,a.karaoke);assert.equal(styled.clips[0].fontSize,70);assert.throws(()=>applyCaptionBatch(p,[a.id],{find:a.text,replace:'',punctuation:'keep',lineLength:0}),/沒有文字/);});
test('line wrapping preserves graphemes and overlap checks do not confuse separate subtitle tracks',()=>{assert.equal(wrapCaption('你好👨‍👩‍👧‍👦世界',3),'你好👨‍👩‍👧‍👦\n世界');const a=makeClip({kind:'text',trackId:'text',start:0,duration:100});const b={...a,id:uid(),start:30,duration:10},c={...a,id:uid(),start:90,duration:20},d={...a,id:uid(),trackId:'overlay'};assert.deepEqual(captionOverlaps([a,b,c,d]),new Set([a.id,b.id,c.id]));});
