import { test,expect } from '@playwright/test';
import {newProject,makeClip} from '../../shared/model';
test('manual word timing rejects missing times, previews, persists, exports and invalidates edited text',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const p=newProject();p.name='卡拉 OK 校時測試';p.clips=[makeClip({kind:'text',trackId:'text',start:0,duration:120,text:'星光',name:'星光',fontSize:180})];
 expect((await page.request.put(`/api/projects/${p.id}`,{headers:{'X-MyCut':'1'},data:p})).ok()).toBeTruthy();await page.goto('/');await page.getByRole('button',{name:'開啟 卡拉 OK 校時測試',exact:true}).click();await page.locator('.timeline-clip').filter({hasText:'星光'}).click();await page.locator('.inspector').getByRole('button',{name:'文字',exact:true}).click();await expect(page.getByLabel('啟用卡拉 OK 高亮')).toBeDisabled();await page.getByRole('button',{name:'逐字校時',exact:true}).click();const modal=page.getByRole('dialog',{name:'逐字校時'});
 await modal.getByRole('button',{name:'按字重新分段'}).click();await modal.getByRole('button',{name:'儲存逐字時間'}).click();await expect(modal.getByRole('alert')).toContainText('每個字詞');await modal.getByLabel('字詞 1 起點',{exact:true}).fill('0');await modal.getByLabel('字詞 1 終點',{exact:true}).fill('1');await modal.getByLabel('字詞 2 起點',{exact:true}).fill('1.5');await modal.getByLabel('字詞 2 終點',{exact:true}).fill('3');await expect(modal).toContainText('2 個字詞已對齊');
 await modal.getByRole('button',{name:'播放第 1 字',exact:true}).click();await expect(modal.getByRole('button',{name:'暫停校時播放'})).toBeVisible();await modal.getByRole('button',{name:'播放第 2 字',exact:true}).click();await page.waitForTimeout(250);expect(parseFloat(await modal.locator('.karaoke-transport output').innerText())).toBeGreaterThan(1.5);await expect(modal.getByRole('button',{name:'暫停校時播放'})).toBeVisible();await modal.getByRole('button',{name:'暫停校時播放'}).click();await page.screenshot({path:'test-results/karaoke-timing.png',fullPage:true});await modal.getByRole('button',{name:'儲存逐字時間'}).click();await expect(modal).toHaveCount(0);await expect(page.getByLabel('啟用卡拉 OK 高亮')).toBeChecked();await expect(page.getByText('已儲存至本機',{exact:true})).toBeVisible();
 let saved=await(await page.request.get(`/api/projects/${p.id}`)).json();expect(saved.clips[0].karaoke.words).toEqual([{text:'星',start:0,end:30},{text:'光',start:45,end:90}]);await expect(page.locator('.inspector').getByRole('button',{name:/匯出/})).toHaveCount(0);await page.getByRole('navigation').getByRole('button',{name:'字幕',exact:true}).click();const downloaded=page.waitForEvent('download');await page.locator('.library-panel').getByRole('button',{name:'匯出所選歌詞 LRC',exact:true}).click();const artifact=await downloaded;expect(artifact.suggestedFilename()).toMatch(/\.word.lrc$/);let exported='';for await(const chunk of (await artifact.createReadStream())!)exported+=chunk.toString();expect(exported).toBe('[00:00.00]<00:00.00>星<00:01.50>光<00:03.00>');
 await page.getByRole('button',{name:'返回專案首頁'}).click();await page.reload();await page.getByRole('button',{name:'開啟 卡拉 OK 校時測試',exact:true}).click();await page.locator('.timeline-clip').filter({hasText:'星光'}).click();await page.locator('.inspector').getByRole('button',{name:'文字',exact:true}).click();await expect(page.getByLabel('啟用卡拉 OK 高亮')).toBeChecked();await page.getByLabel('文字內容',{exact:true}).fill('星空');await expect(page.getByLabel('啟用卡拉 OK 高亮')).toBeDisabled();await page.getByRole('navigation').getByRole('button',{name:'字幕',exact:true}).click();await expect(page.getByRole('button',{name:'匯出所選歌詞 LRC',exact:true})).toBeDisabled();await page.getByRole('button',{name:/^復原（/}).click();await expect(page.getByLabel('啟用卡拉 OK 高亮')).toBeChecked();expect(errors).toEqual([]);
});
