import { test, expect } from '@playwright/test';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';


test('home starts without phantom projects and supports create, rename, copy, trash, restore and project files',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{name:'我的專案'})).toBeVisible();await expect(page.locator('.loading-screen')).toHaveCount(0);
 const count=(await(await page.request.get('/api/projects')).json()).length;await page.keyboard.press('m');expect((await(await page.request.get('/api/projects')).json()).length).toBe(count);
 await page.getByRole('button',{name:'建立新專案',exact:true}).click();await expect(page.locator('.project-switch')).toContainText('未命名專案');await expect(page.getByRole('dialog',{name:'建立新專案'})).toHaveCount(0);await expect(page.locator('.timeline-footer')).toContainText('0 個片段');
 await page.getByRole('button',{name:'返回專案首頁'}).click();await expect(page.locator('.project-home')).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'開啟 未命名專案',exact:true})).toBeVisible();const all=await(await page.request.get('/api/projects')).json();expect(all).toHaveLength(count+1);const saved=all.find((p:any)=>p.name==='未命名專案');expect(saved.width).toBe(1920);expect(saved.height).toBe(1080);expect(saved.fps).toBe(30);
 await page.getByRole('button',{name:'重新命名 未命名專案',exact:true}).click();await page.getByRole('dialog',{name:'重新命名專案'}).getByLabel('專案名稱').fill('我的剪輯專案');await page.getByRole('button',{name:'儲存名稱'}).click();await expect(page.getByRole('button',{name:'開啟 我的剪輯專案',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'複製 我的剪輯專案',exact:true}).click();await expect(page.getByRole('button',{name:'開啟 我的剪輯專案 · 副本',exact:true})).toBeVisible();await page.getByLabel('搜尋專案').fill('我的剪輯');await expect(page.locator('.project-card')).toHaveCount(2);await page.screenshot({path:'test-results/project-home.png',fullPage:true});
 await page.getByRole('button',{name:'移至回收區 我的剪輯專案',exact:true}).click();await expect(page.getByRole('button',{name:'開啟 我的剪輯專案',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'回收區',exact:true}).click();await page.getByRole('button',{name:'還原 我的剪輯專案',exact:true}).click();await expect(page.getByRole('button',{name:'還原 我的剪輯專案',exact:true})).toHaveCount(0);await page.getByRole('button',{name:/最近專案/}).click();await expect(page.getByRole('button',{name:'開啟 我的剪輯專案',exact:true})).toBeVisible();
 const project=await(await page.request.get(`/api/projects/${saved.id}`)).json();const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'開啟專案檔',exact:true}).click();await(await chooser).setFiles({name:'my-project.mycut.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await expect(page.locator('.project-switch')).toContainText('我的剪輯專案 · 匯入');await page.getByRole('button',{name:'返回專案首頁'}).click();await expect(page.locator('.project-home')).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'開啟 我的剪輯專案 · 匯入',exact:true})).toBeVisible();expect(errors).toEqual([]);
});

test('start from a real audio file, recognize, proofread, apply captions, undo and reload',async({page})=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const temp=await fs.mkdtemp(path.join(os.tmpdir(),'mycut-ui-speech-'));const aiff=path.join(temp,'original.aiff'),wav=path.join(temp,'字幕功能測試.wav');
 await fs.copyFile(path.resolve('tests/fixtures/original-en.wav'),wav);
 await page.goto('/');await expect(page.locator('.loading-screen')).toHaveCount(0);const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'從影片開始',exact:true}).click();await(await chooser).setFiles(wav);await expect(page.locator('.project-switch')).toContainText('字幕功能測試');await expect(page.locator('.timeline-footer')).toContainText('1 個片段');
 await page.getByRole('button',{name:'字幕',exact:true}).click();await expect(page.getByRole('button',{name:'自動字幕',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'自動歌詞',exact:true})).toBeVisible();await page.getByLabel('音訊語言').selectOption('en');await page.getByRole('button',{name:'開始辨識字幕'}).click();await expect(page.getByRole('button',{name:'校對與加入'})).toBeVisible({timeout:120000});await page.getByRole('button',{name:'校對與加入'}).click();const review=page.getByRole('dialog',{name:'校對辨識結果'});await expect(review.getByLabel('字幕 1 文字',{exact:true})).not.toHaveValue('');await review.getByLabel('字幕 1 文字',{exact:true}).fill('校對完成的字幕');await page.screenshot({path:'test-results/caption-review.png',fullPage:true});await review.getByRole('button',{name:'加入時間軸',exact:true}).click();await expect(page.locator('.track-header').filter({hasText:'自動字幕'})).toBeVisible();await expect(page.getByText('已儲存至本機',{exact:true})).toBeVisible();
 const projects=await(await page.request.get('/api/projects')).json();const p=projects.find((p:any)=>p.name==='字幕功能測試');let saved=await(await page.request.get(`/api/projects/${p.id}`)).json();expect(saved.clips.some((c:any)=>c.text==='校對完成的字幕')).toBe(true);const captionCount=saved.clips.filter((c:any)=>c.captionJobId).length;expect(captionCount).toBeGreaterThan(0);
 await page.getByRole('button',{name:/^復原（/}).click();await expect(page.locator('.timeline-footer')).toContainText('1 個片段');await page.getByRole('button',{name:/^重做（/}).click();await expect(page.locator('.timeline-footer')).toContainText(`${captionCount+1} 個片段`);
 await page.getByRole('button',{name:'自動歌詞',exact:true}).click();await expect(page.getByText('減少低頻與高頻伴奏干擾',{exact:true})).toBeVisible();await page.getByRole('button',{name:'開始辨識歌詞'}).click();await expect(page.getByRole('button',{name:'校對與加入'})).toHaveCount(2,{timeout:120000});await page.getByRole('button',{name:'校對與加入'}).first().click();await expect(page.getByRole('button',{name:'LRC',exact:true})).toBeVisible();const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'LRC',exact:true}).click();expect((await downloaded).suggestedFilename()).toMatch(/\.lrc$/);await page.getByRole('button',{name:'關閉校對'}).click();
 await page.getByRole('button',{name:'返回專案首頁'}).click();await page.reload();await page.getByRole('button',{name:'開啟 字幕功能測試',exact:true}).click();saved=await(await page.request.get(`/api/projects/${p.id}`)).json();expect(saved.clips.some((c:any)=>c.text==='校對完成的字幕')).toBe(true);expect(errors).toEqual([]);
});
