import { test, expect } from '@playwright/test';
import { newProject, makeClip, type Project } from '../../shared/model';

async function open(page:any,p:Project){expect((await page.request.put(`/api/projects/${p.id}`,{headers:{'X-MyCut':'1'},data:p})).ok()).toBeTruthy();await page.goto('/');await page.getByRole('button',{name:`開啟 ${p.name}`,exact:true}).click();await expect(page.getByRole('button',{name:'匯出影片',exact:true})).toBeVisible();}
const read=async(page:any,p:Project)=>await(await page.request.get(`/api/projects/${p.id}`)).json() as Project;

test('multi-selection groups move and duplicate together, undo and reload retain relations',async({page})=>{
  const p=newProject();p.name='多選群組驗證';p.clips=[makeClip({kind:'shape',trackId:'main',start:0,duration:120,name:'底圖'}),makeClip({kind:'shape',trackId:'overlay',start:60,duration:60,name:'疊圖'})];await open(page,p);
  await page.getByRole('button',{name:'底圖，00:00:00:00'}).click();await page.getByRole('button',{name:'疊圖，00:00:02:00'}).click({modifiers:['Shift']});await expect(page.locator('.timeline-clip.selected')).toHaveCount(2);
  await page.getByRole('button',{name:'建立群組',exact:true}).click();const clip=page.getByRole('button',{name:'底圖，00:00:00:00'}),box=(await clip.boundingBox())!;await page.mouse.move(box.x+25,box.y+20);await page.mouse.down();await page.mouse.move(box.x+80,box.y+20,{steps:5});await page.mouse.up();
  await expect.poll(async()=> (await read(page,p)).clips.map(c=>c.start)).toEqual([30,90]);
  await page.getByRole('button',{name:/^複製片段（/}).click();await expect(page.locator('.timeline-clip')).toHaveCount(4);await page.getByRole('button',{name:/^復原（/}).click();await expect(page.locator('.timeline-clip')).toHaveCount(2);await page.getByRole('button',{name:/^重做（/}).click();await expect(page.locator('.timeline-clip')).toHaveCount(4);
  await expect.poll(async()=> (await read(page,p)).clips.length).toBe(4);const saved=await read(page,p);expect(saved.clips[0].groupId).toBe(saved.clips[1].groupId);expect(saved.clips[2].groupId).toBe(saved.clips[3].groupId);expect(saved.clips[2].groupId).not.toBe(saved.clips[0].groupId);
  await page.reload();await page.getByRole('button',{name:`開啟 ${p.name}`,exact:true}).click();await page.getByRole('button',{name:'底圖，00:00:01:00'}).click();await expect(page.locator('.timeline-clip.selected')).toHaveCount(2);await page.getByRole('button',{name:'解除群組',exact:true}).click();await page.getByRole('button',{name:'底圖，00:00:01:00'}).click({modifiers:['Shift']});await expect(page.locator('.timeline-clip.selected')).toHaveCount(1);
});
test('marquee selects clips across tracks without moving or modifying them',async({page})=>{
  const p=newProject();p.name='框選驗證';p.clips=[makeClip({kind:'shape',trackId:'overlay',start:60,duration:60,name:'框選 A'}),makeClip({kind:'shape',trackId:'main',start:90,duration:60,name:'框選 B'})];await open(page,p);
  const upper=(await page.locator('[data-track=overlay]').boundingBox())!,lower=(await page.locator('[data-track=main]').boundingBox())!;
  await page.mouse.move(upper.x+90,upper.y+5);await page.mouse.down();await page.mouse.move(lower.x+285,lower.y+lower.height-5,{steps:8});await page.mouse.up();await expect(page.locator('.timeline-clip.selected')).toHaveCount(2);await expect(page.locator('.timeline-marquee')).toHaveCount(0);expect((await read(page,p)).clips.map(c=>c.start)).toEqual([60,90]);
});
test('timed effect cards create editable clips with independent duration, fades and strength animation',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const p=newProject();p.name='時段特效驗證';p.clips=[makeClip({kind:'shape',trackId:'main',start:0,duration:150,color:'#428679'})];await open(page,p);
  await page.getByRole('navigation').getByRole('button',{name:'特效',exact:true}).click();await page.getByRole('button',{name:'時段特效',exact:true}).click();await page.getByRole('button',{name:'雨絲',exact:true}).click();await expect(page.locator('.clip-effect')).toHaveCount(1);await page.getByLabel('特效開始秒數',{exact:true}).fill('1');await page.getByLabel('特效長度秒數',{exact:true}).fill('2');await page.getByLabel('特效淡入',{exact:true}).focus();await page.keyboard.press('End');
  await page.getByRole('button',{name:'加入強度關鍵影格',exact:true}).click();await page.getByLabel('片段特效強度',{exact:true}).focus();await page.keyboard.press('Home');await page.getByRole('button',{name:'回到開頭',exact:true}).click();await page.keyboard.press('Shift+ArrowRight');await page.keyboard.press('Shift+ArrowRight');await page.getByRole('button',{name:'加入強度關鍵影格',exact:true}).click();await page.getByLabel('片段特效強度',{exact:true}).focus();await page.keyboard.press('End');
  await expect.poll(async()=> (await read(page,p)).clips.find(c=>c.kind==='effect')?.keyframes.length).toBe(2);const saved=await read(page,p),fx=saved.clips.find(c=>c.kind==='effect')!;expect([fx.start,fx.duration,fx.fadeIn]).toEqual([30,60,60]);expect(fx.keyframes.map(k=>[k.frame,k.opacity])).toEqual([[0,0],[30,1]]);expect(saved.effects.enabled).toEqual([]);
  await page.screenshot({path:'test-results/timed-effects.png',fullPage:true});await page.reload();await page.getByRole('button',{name:`開啟 ${p.name}`,exact:true}).click();await page.getByRole('button',{name:'雨絲，00:00:01:00'}).click();await expect(page.getByLabel('特效長度秒數',{exact:true})).toHaveValue('2');expect(errors).toEqual([]);
});
test('caption batch previews scoped replacements, overlap warnings and styles as one undo step',async({page})=>{
  const p=newProject();p.name='字幕批次驗證';p.clips=[makeClip({kind:'text',trackId:'text',captionType:'captions',start:0,duration:90,text:'Hello,世界!'}),makeClip({kind:'text',trackId:'text',captionType:'lyrics',start:60,duration:90,text:'Hello,晚安!'}),makeClip({kind:'text',trackId:'overlay',start:0,duration:150,text:'Hello,片頭!',name:'片頭'})];await open(page,p);
  await page.getByRole('navigation').getByRole('button',{name:'字幕',exact:true}).click();await page.getByRole('button',{name:'字幕批次編輯',exact:true}).click();await expect(page.locator('.batch-row')).toHaveCount(2);await expect(page.locator('.batch-summary')).toContainText('同軌時間重疊：2 則');await page.getByLabel('批次尋找').fill('Hello');await page.getByLabel('批次取代').fill('你好');await page.getByLabel('批次標點').selectOption('traditional');await page.getByLabel('每行最多字數').fill('3');await page.getByLabel('批次套用樣式').check();await page.getByLabel('批次字型').selectOption('huninn');await page.getByLabel('批次字級').fill('72');await page.getByRole('button',{name:'預覽套用（2 則）'}).click();await expect(page.locator('.batch-row').first()).toContainText('你好，\n世界！');await expect(page.locator('.batch-footer')).toContainText('已變更 2 則');await page.screenshot({path:'test-results/caption-batch.png',fullPage:true});
  expect((await read(page,p)).clips[0].text).toBe('Hello,世界!');await page.getByRole('button',{name:'儲存批次變更'}).click();await expect.poll(async()=> (await read(page,p)).clips[0].text).toBe('你好，\n世界！');const edited=await read(page,p);expect(edited.clips[0].fontId).toBe('huninn');expect(edited.clips[1].fontSize).toBe(72);expect(edited.clips[2].text).toBe('Hello,片頭!');await page.getByRole('button',{name:/^復原（/}).click();await expect.poll(async()=> (await read(page,p)).clips[0].text).toBe('Hello,世界!');expect((await read(page,p)).clips[0].fontId).toBe('notosanstc');
});
