import { useState, useEffect } from 'react';
import KaraokePanel from './KaraokePanel';
import FontLibrary from './FontLibrary';
import CaptionProperties from './CaptionProperties';
import { SlidersHorizontal, Diamond, RotateCcw, FlipHorizontal2, FlipVertical2, ChevronDown, Volume2, Info } from 'lucide-react';
import { patchLinkedClip, compatibleTrack } from '../../shared/editing';
import { clamp, evaluateClip, timecode, type Clip, type FontInfo, type Media, type Project } from '../../shared/model';
type Props={onSelectCaption:(clip:Clip)=>void;project:Project;clip?:Clip;media:Media[];fonts:FontInfo[];fontFavorites:string[];defaultFontId:string;fontSaving:boolean;onFontFavorite:(id:string,checked:boolean)=>void;frame:number;update:(fn:(p:Project)=>Project,history?:boolean)=>void;playing:boolean;onSeek:(frame:number)=>void;onPlaying:(playing:boolean)=>void;onError:(e:unknown)=>void};
function Slider({label,value,min,max,step=1,unit='',onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(n:number)=>void}){return <label className="slider-field"><span>{label}<output>{Number(value.toFixed(2))}{unit}</output></span><input type="range" aria-label={label} min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label>;}
export default function Inspector({onSelectCaption,project:p,clip:c,media,fonts,fontFavorites,defaultFontId,fontSaving,onFontFavorite,frame,update,playing,onSeek,onPlaying,onError}:Props){
 const [tab,setTab]=useState('basic');
 useEffect(()=>{setTab(tab=>c?.kind==='text'?(tab==='captions'?'captions':'basic'):(tab==='captions'?'basic':tab));},[c?.id,c?.kind]);
 useEffect(()=>{if(tab==='audio'&&c?.kind!=='audio'&&!(c?.kind==='video'&&media.find(m=>m.id===c.mediaId)?.hasAudio))setTab('basic');},[c?.id,c?.kind,media,tab]);
 useEffect(()=>{if(c?.kind==='audio'&&(tab==='color'||tab==='motion'))setTab('audio');},[c?.kind,tab]);
 const patch=(fields:Partial<Clip>)=>{if(!c)return;try{if(fields.text!==undefined&&fields.text!==c.text&&!fields.karaoke)fields={...fields,karaoke:{...c.karaoke,enabled:false}};
   if(['x','y','scale','opacity'].some(k=>k in fields)&&c.keyframes.length){const relative=clamp(frame-c.start,0,c.duration);fields={...fields,keyframes:[...c.keyframes.filter(k=>k.frame!==relative),{frame:relative,...evaluateClip(c,relative),...Object.fromEntries(Object.entries(fields).filter(([k])=>['x','y','scale','opacity'].includes(k)))}].sort((a,b)=>a.frame-b.frame)};}
   update(p=>patchLinkedClip(p,c.id,fields,media));
 }catch(e){onError(e);}};
 const field=(key:keyof Clip,label:string,min:number,max:number,step=1,unit='')=><Slider label={label} value={Number(c?.[key]??0)} min={min} max={max} step={step} unit={unit} onChange={v=>patch({[key]:v})}/>;
 const changeProject=(width:number,height:number)=>update(p=>({...p,width,height}));
 const source=media.find(m=>m.id===c?.mediaId);const relative=c?clamp(frame-c.start,0,c.duration):0;const state=c?evaluateClip(c,relative):null;
 const keyframe=()=>{if(!c)return;const keys=c.keyframes;const has=keys.some(k=>k.frame===relative);patch({keyframes:has?keys.filter(k=>k.frame!==relative):[...keys,{frame:relative,...evaluateClip(c,relative)}].sort((a,b)=>a.frame-b.frame)});};
 return <aside className="inspector"><div className="panel-header"><span>{c?'片段屬性':'專案設定'}</span><SlidersHorizontal size={15}/></div>
 {!c?<div className="inspector-scroll"><h3 className="project-settings-name">{p.name}</h3><section className="property-section"><h4>畫布比例</h4><div className="aspect-options">{[['16:9',1920,1080],['9:16',1080,1920],['1:1',1080,1080],['4:3',1440,1080],['4:5',1080,1350],['21:9',2520,1080]].map(([label,w,h])=><button key={label} className={Math.abs(p.width/p.height-Number(w)/Number(h))<.01?'chosen':''} onClick={()=>changeProject(+w,+h)}>{label}</button>)}</div><label className="select-field"><span>影格率</span><select aria-label="專案影格率" value={p.fps} disabled={p.clips.length>0} onChange={e=>update(p=>({...p,fps:+e.target.value as Project['fps']}))}>{[24,25,30,50,60].map(f=><option key={f} value={f}>{f} fps</option>)}</select></label>{p.clips.length>0&&<p className="field-note">影格率在空白專案中設定，避免改變既有剪輯節奏。</p>}<label className="color-field">背景顏色<input aria-label="背景顏色" type="color" value={p.background} onChange={e=>update(p=>({...p,background:e.target.value}))}/><span>{p.background.toUpperCase()}</span></label></section><details className="compact-details"><summary>專案資訊</summary><dl className="info-list"><dt>解析度</dt><dd>{p.width} × {p.height}</dd><dt>字型</dt><dd>{fonts.length} 款 · 免費商用</dd><dt>自動儲存</dt><dd className="accent">已啟用</dd><dt>媒體處理</dt><dd>本機原生引擎</dd></dl></details><div className="tip"><Info size={15}/><p>選取時間軸上的片段，即可調整畫面、文字、動畫與音訊。</p></div></div>:
 <><div className="inspector-tabs">{[['captions','字幕'],['basic',c.kind==='text'?'文字':'基本'],['motion','動畫'],['color','調色'],['audio','音訊']].filter(([key])=>(key!=='captions'||c.kind==='text')&&(key!=='audio'||c.kind==='audio'||c.kind==='video'&&!!source?.hasAudio)&&(c.kind!=='audio'||key==='basic'||key==='audio')).map(([key,label])=><button key={key} aria-label={key==='captions'?'字幕屬性':undefined} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div><div className="inspector-scroll">{tab!=='captions'&&<div className="clip-heading"><span className={`clip-dot ${c.kind}`}/><input aria-label="片段名稱" value={c.name} onChange={e=>patch({name:e.target.value})}/></div>}
 {c.kind==='text'&&<CaptionProperties project={p} clip={c} active={tab==='captions'} onSelect={onSelectCaption}/> }
 {tab==='basic'&&<> {c.kind==='text'&&<section className="property-section"><h4>文字內容</h4><textarea aria-label="文字內容" value={c.text} rows={3} onChange={e=>patch({text:e.target.value})}/><FontLibrary fonts={fonts} favorites={fontFavorites} defaultId={defaultFontId} saving={fontSaving} onFavorite={onFontFavorite} selectedId={c.fontId} onSelect={id=>patch({fontId:id})}/>{field('fontSize','字級',12,300)}<label className="color-field">文字顏色<input aria-label="文字顏色" type="color" value={c.color} onChange={e=>patch({color:e.target.value})}/><span>{c.color.toUpperCase()}</span></label><label className="check-field"><input type="checkbox" checked={c.textBackground} onChange={e=>patch({textBackground:e.target.checked})}/>文字背景底色</label></section>}{c.kind==='text'&&<KaraokePanel key={c.id} clip={c} fps={p.fps} frame={frame} playing={playing} fonts={fonts} projectWidth={p.width} onSeek={onSeek} onPlaying={onPlaying} onChange={patch}/>}<section className="property-section"><h4>時間與位置</h4><div className="number-pair"><label>開始（秒）<input aria-label="開始秒數" type="number" min="0" step={1/p.fps} value={Number((c.start/p.fps).toFixed(3))} onChange={e=>patch({start:Math.max(0,Math.round(+e.target.value*p.fps))})}/></label><label>長度（秒）<input aria-label="片段長度" type="number" min={1/p.fps} step={1/p.fps} value={Number((c.duration/p.fps).toFixed(3))} onChange={e=>{const max=source&&source.kind!=='image'?Math.floor((source.duration-c.sourceIn)/c.speed*p.fps):86400*p.fps;patch({duration:clamp(Math.round(+e.target.value*p.fps),1,Math.max(1,max))});}}/></label></div><label className="select-field"><span>所在軌道</span><select aria-label="所在軌道" value={c.trackId} onChange={e=>patch({trackId:e.target.value})}>{p.tracks.filter(t=>!t.locked&&compatibleTrack(c.kind,t)).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></section>


 {c.kind==='shape'&&<section className="property-section"><h4>圖形</h4><label className="color-field">填色<input aria-label="圖形顏色" type="color" value={c.color} onChange={e=>patch({color:e.target.value})}/><span>{c.color}</span></label><select aria-label="圖形種類" value={c.shape} onChange={e=>patch({shape:e.target.value as Clip['shape']})}><option value="rectangle">圓角矩形</option><option value="circle">圓形</option></select></section>}
 {c.kind!=='audio'&&<section className="property-section"><h4>變形<button data-tooltip="重設變形" aria-label="重設變形" onClick={()=>patch({x:0,y:0,scale:1,rotation:0,opacity:1,flipX:false,flipY:false,crop:0,keyframes:[]})}><RotateCcw size={13}/></button></h4><Slider label="縮放" value={state!.scale*100} min={5} max={400} unit="%" onChange={v=>patch({scale:v/100})}/><div className="number-pair"><label>位置 X<input aria-label="位置 X" type="number" step="1" value={Math.round(state!.x*p.width)} onChange={e=>patch({x:clamp(+e.target.value/p.width,-2,2)})}/></label><label>位置 Y<input aria-label="位置 Y" type="number" step="1" value={Math.round(state!.y*p.height)} onChange={e=>patch({y:clamp(+e.target.value/p.height,-2,2)})}/></label></div>{field('rotation','旋轉',-180,180,1,'°')}<Slider label="不透明度" value={state!.opacity*100} min={0} max={100} unit="%" onChange={v=>patch({opacity:v/100})}/><div className="button-pair"><button className={c.flipX?'chosen':''} onClick={()=>patch({flipX:!c.flipX})}><FlipHorizontal2 size={14}/>水平翻轉</button><button className={c.flipY?'chosen':''} onClick={()=>patch({flipY:!c.flipY})}><FlipVertical2 size={14}/>垂直翻轉</button></div><label className="select-field"><span>畫面填滿</span><select aria-label="畫面填滿" value={c.fit} onChange={e=>patch({fit:e.target.value as Clip['fit']})}><option value="contain">完整顯示</option><option value="cover">裁切填滿</option></select></label>{field('crop','中心裁切',0,.45,.01)}</section>}
 {(c.kind==='video'||c.kind==='audio')&&<section className="property-section"><h4>播放速度</h4><Slider label="速度" value={c.speed} min={.25} max={4} step={.05} unit="×" onChange={v=>patch({speed:v,duration:Math.max(1,Math.round(c.duration*c.speed/v)),keyframes:c.keyframes.map(k=>({...k,frame:Math.round(k.frame*c.speed/v)}))})}/><p className="field-note">變速保留音高；片段長度會跟著調整。</p></section>}</>}
 {tab==='motion'&&<><section className="property-section"><h4>關鍵影格</h4><p className="field-note">移動播放頭後加入關鍵影格，再到「{c.kind==='text'?'文字':'基本'}」調整位置、縮放及不透明度。</p><button className="wide-button" onClick={keyframe}><Diamond size={15} fill={c.keyframes.some(k=>k.frame===relative)?'currentColor':'none'}/>{c.keyframes.some(k=>k.frame===relative)?'移除此關鍵影格':'新增關鍵影格'}</button><div className="keyframe-list">{c.keyframes.map(k=><div key={k.frame}><Diamond size={11}/><span>{timecode(k.frame,p.fps)}</span><span>{Math.round(k.scale*100)}%</span><button data-tooltip={`移除 ${timecode(k.frame,p.fps)} 關鍵影格`} aria-label={`移除 ${timecode(k.frame,p.fps)} 關鍵影格`} onClick={()=>patch({keyframes:c.keyframes.filter(x=>x.frame!==k.frame)})}>×</button></div>)}</div></section><section className="property-section"><h4>進出場</h4><Slider label="淡入" value={c.fadeIn/p.fps} min={0} max={Math.min(5,c.duration/p.fps)} step={.1} unit="s" onChange={v=>patch({fadeIn:Math.round(v*p.fps)})}/><Slider label="淡出" value={c.fadeOut/p.fps} min={0} max={Math.min(5,c.duration/p.fps)} step={.1} unit="s" onChange={v=>patch({fadeOut:Math.round(v*p.fps)})}/></section></>}
 {tab==='color'&&<><section className="property-section"><h4>色彩調整<button data-tooltip="重設調色" aria-label="重設調色" onClick={()=>patch({brightness:0,contrast:1,saturation:1,blur:0,chroma:false})}><RotateCcw size={13}/></button></h4>{field('brightness','亮度',-.8,.8,.01)}{field('contrast','對比',.1,3,.01)}{field('saturation','飽和度',0,3,.01)}{field('blur','模糊',0,20,.5)}</section><section className="property-section"><h4>色度去背</h4><label className="check-field"><input type="checkbox" checked={c.chroma} onChange={e=>patch({chroma:e.target.checked})}/>啟用綠幕／色度去背</label>{c.chroma&&<><label className="color-field">移除顏色<input aria-label="去背顏色" type="color" value={c.chromaColor} onChange={e=>patch({chromaColor:e.target.value})}/></label>{field('chromaSimilarity','容差',.01,.5,.01)}</>}</section><p className="field-note">預覽使用輕量色彩處理，精確顏色與去背邊緣以原生匯出為準。</p></>}
 {tab==='audio'&&<><section className="property-section"><h4>音訊</h4><Slider label="音量" value={c.volume*100} min={0} max={200} unit="%" onChange={v=>patch({volume:v/100})}/><Slider label="音訊淡入" value={c.audioFadeIn/p.fps} min={0} max={Math.min(10,c.duration/p.fps)} step={.1} unit="s" onChange={v=>patch({audioFadeIn:Math.round(v*p.fps)})}/><Slider label="音訊淡出" value={c.audioFadeOut/p.fps} min={0} max={Math.min(10,c.duration/p.fps)} step={.1} unit="s" onChange={v=>patch({audioFadeOut:Math.round(v*p.fps)})}/><label className="check-field"><input type="checkbox" checked={c.denoise} onChange={e=>patch({denoise:e.target.checked})}/>匯出時降低穩態背景噪音</label></section><div className="tip"><Volume2 size={15}/><p>混音使用立體聲 48 kHz，匯出會限制峰值以減少爆音。</p></div></>}
 {source&&<section className="property-section source-info"><h4>來源資訊</h4><p>{source.name}</p><span>{source.width?`${source.width} × ${source.height} · `:''}{(source.size/1024**2).toFixed(1)} MB</span></section>}
 </div></>}
 </aside>;
}
