import { useRef, useState, type ReactNode } from 'react';
import { Sparkles, Upload, Search, Plus, Film, Music2, Image, Type, Captions, SlidersHorizontal, Blend, Shapes, ArrowUpRight, Check, Download, Mic, Square, Circle, LoaderCircle, Link2, FolderOpen, Unlink2 } from 'lucide-react';
import { shortTime, type Clip, type Media } from '../../shared/model';
export type LibraryTab='media'|'audio'|'text'|'captions'|'effects'|'atmosphere'|'transitions'|'shapes';
const tabs=[{id:'media',name:'素材',icon:Film},{id:'audio',name:'音訊',icon:Music2},{id:'text',name:'文字',icon:Type},{id:'captions',name:'字幕',icon:Captions},{id:'atmosphere',name:'特效',icon:Sparkles},{id:'effects',name:'濾鏡',icon:SlidersHorizontal},{id:'transitions',name:'轉場',icon:Blend},{id:'shapes',name:'圖形',icon:Shapes}] as const;
const presets=[{name:'原始',description:'Original',brightness:0,contrast:1,saturation:1,blur:0},{name:'電影感',description:'Cinema',brightness:-.04,contrast:1.24,saturation:.78,blur:0},{name:'日常',description:'Everyday',brightness:.06,contrast:1.05,saturation:1.12,blur:0},{name:'黑白',description:'Monochrome',brightness:0,contrast:1.2,saturation:0,blur:0},{name:'淡彩',description:'Soft',brightness:.08,contrast:.85,saturation:.75,blur:0},{name:'濃郁',description:'Vivid',brightness:0,contrast:1.15,saturation:1.55,blur:0},{name:'低光',description:'Night',brightness:-.15,contrast:1.3,saturation:.65,blur:0},{name:'柔焦',description:'Dream',brightness:.05,contrast:.95,saturation:.9,blur:4}];
type Props={effectTools:ReactNode;captionTools:ReactNode;tab:LibraryTab;media:Media[];busy:boolean;onImport:()=>void;onFiles:(files:File[])=>void;onAdd:(id:string)=>void;onText:(style?:string)=>void;onShape:(shape:'rectangle'|'circle')=>void;onCaptionImport:(f:File)=>void;onCaptionExport:()=>void;onWordLrcExport:()=>void;canExportWordLrc:boolean;onDetach:()=>void;canDetach:boolean;onEffect:(v:Partial<Clip>)=>void;onTransition:(kind:string)=>void;onProxy:(id:string)=>void;onRelink:(id:string)=>void;onDemo:()=>void;onRecord:()=>void;recording:boolean;selected?:Clip};
export function LibraryNav({tab,setTab}:{tab:LibraryTab;setTab:(tab:LibraryTab)=>void}){return <nav className="tool-nav">{tabs.map(t=><button key={t.id} data-tooltip={t.name} aria-label={t.name} aria-pressed={tab===t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}><t.icon size={21} strokeWidth={1.65}/></button>)}</nav>;}
export default function LibraryPanel({effectTools,captionTools,tab,media,busy,onImport,onFiles,onAdd,onText,onShape,onCaptionImport,onCaptionExport,onWordLrcExport,canExportWordLrc,onDetach,canDetach,onEffect,onTransition,onProxy,onRelink,onDemo,onRecord,recording,selected}:Props){
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const input=useRef<HTMLInputElement>(null);const [drag,setDrag]=useState(false);const title=tabs.find(t=>t.id===tab)?.name;
 const visible=media.filter(m=>(tab!=='audio'||m.kind==='audio')&&(filter==='all'||m.kind===filter)&&m.name.toLowerCase().includes(query.toLowerCase()));
 return <aside className="library-panel"><div className="panel-header"><span>{title}</span>{(tab==='media'||tab==='audio')&&<span className="badge">{media.filter(m=>tab!=='audio'||m.kind==='audio').length}</span>}</div><div className="library-scroll">
 {(tab==='media'||tab==='audio')&&<><div className={`import-zone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);onFiles(Array.from(e.dataTransfer.files));}}><button className="import-button" onClick={onImport} disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:<Plus size={18}/>} {busy?'正在匯入…':'匯入素材'}</button><p>或拖入影片、圖片、音訊</p></div><label className="search-box"><Search size={14}/><input aria-label="搜尋素材" placeholder="搜尋素材" value={query} onChange={e=>setQuery(e.target.value)}/></label>{tab==='media'&&<div className="filter-chips">{[['all','全部'],['video','影片'],['image','圖片'],['audio','音訊']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div>}
 {tab==='audio'&&<button className={`record-button ${recording?'recording':''}`} onClick={onRecord}>{recording?<Square size={14} fill="currentColor"/>:<Mic size={16}/>} {recording?'停止錄音並加入素材':'錄製旁白'}</button>}
 {tab==='audio'&&<button className="wide-button" disabled={!canDetach} data-tooltip={canDetach?undefined:selected?.linkId?'請先解除音畫連動':'選取未鎖定且含音訊的影片'} onClick={onDetach}><Unlink2 size={15}/>分離音訊</button>}
 <div className="media-grid">{visible.map(m=><div className={`media-card ${m.missing?'missing':''}`} key={m.id} draggable onDragStart={e=>{e.dataTransfer.setData('mycut/media',m.id);e.dataTransfer.effectAllowed='copy';}}><button className="media-thumbnail" data-tooltip={`加入 ${m.name}`} aria-label={`加入 ${m.name}`} onClick={()=>onAdd(m.id)}>{m.thumbnail?<img src={m.thumbnail} alt="" loading="lazy"/>:<div className="audio-art"><Music2 size={28}/><div className="mini-bars">{Array.from({length:16},(_,i)=><i key={i} style={{height:8+(Math.sin(i*5)+1)*10}}/>)}</div></div>}<span className="media-kind">{m.kind==='video'?<Film size={11}/>:m.kind==='audio'?<Music2 size={11}/>:<Image size={11}/>}</span><span className="media-duration">{m.kind==='image'?'圖片':shortTime(m.duration)}</span><span className="media-add"><Plus size={16}/></span></button><div className="media-name" title={m.name}>{m.name}</div><div className="media-meta"><span>{m.missing?'來源已移動':m.kind==='audio'?'AUDIO':`${m.width} × ${m.height}`}</span>{m.missing?<button data-tooltip="重新連結" aria-label="重新連結" onClick={()=>onRelink(m.id)}><Link2 size={11}/></button>:m.kind==='video'&&<button data-tooltip="建立 540p 代理檔，加快預覽（匯出使用原檔）" aria-label="建立 540p 代理檔，加快預覽（匯出使用原檔）" onClick={()=>onProxy(m.id)}>{m.proxyStatus==='ready'?<Check size={11}/>:m.proxyStatus==='processing'||m.proxyStatus==='queued'?<LoaderCircle size={11} className="spin"/>:'代理'}</button>}</div></div>)}</div>
 {!visible.length&&<div className="library-empty"><FolderOpen size={26}/><p>{query?'找不到符合的素材':'把靈感帶進來'}</p><span>素材匯入後會出現在這裡</span></div>}</>}
 {tab==='text'&&<><button className="wide-button primary-soft" onClick={()=>onText()}><Plus size={16}/>新增文字</button><div className="section-label">文字樣式</div><div className="text-presets">{[['editorial','宋體','慢下來，看見更多。'],['english','英文標題','MAKE IT YOURS.']].map(([id,label,sample])=><button key={id} onClick={()=>onText(id)} className={`text-preset preset-${id}`}><span>{sample}</span><small>{label}<Plus size={13}/></small></button>)}</div></>}
 {tab==='captions'&&<>{captionTools}<div className="section-label">手動字幕與檔案</div><button className="wide-button primary-soft" onClick={()=>onText('subtitle')}><Plus size={15}/>新增字幕</button><div className="caption-file-actions"><button className="wide-button" aria-label="匯入 SRT 字幕" data-tooltip="匯入 SRT 字幕" onClick={()=>input.current?.click()}><Upload size={15}/>匯入 SRT</button><button className="wide-button" aria-label="匯出 SRT 字幕" data-tooltip="匯出 SRT 字幕" onClick={onCaptionExport}><Download size={15}/>匯出 SRT</button></div><button className="wide-button" disabled={!canExportWordLrc} data-tooltip={canExportWordLrc?undefined:'選取已完成逐字校時的文字片段'} onClick={onWordLrcExport}><Download size={15}/>匯出所選歌詞 LRC</button><input ref={input} type="file" accept=".srt" hidden onChange={e=>{const f=e.target.files?.[0];if(f)onCaptionImport(f);e.target.value='';}}/></>}
 {tab==='atmosphere'&&effectTools}
 {tab==='effects'&&<>{!selected&&<p className="selection-note">先選取一個畫面片段</p>}<div className="effects-grid">{presets.map(p=><button key={p.name} aria-label={`套用${p.name}濾鏡`} data-tooltip={`套用${p.name}濾鏡`} disabled={!selected||selected.kind==='audio'||selected.kind==='effect'} className="effect-card" onClick={()=>{const {name,description,...effect}=p;onEffect(effect);}}><div className="effect-art"><img src={`/artwork/filters/${p.description.toLowerCase()}.svg`} alt="" loading="lazy" decoding="async" draggable={false}/></div><span>{p.name}<small>{p.description}</small></span></button>)}</div></>}
 {tab==='transitions'&&<>{!selected&&<p className="selection-note">先選取一個畫面片段</p>}<div className="transition-grid">{[['fade','淡入淡出'],['dissolve','交叉溶解'],['in','淡入'],['out','淡出'],['none','移除淡化']].map(([id,label])=><button key={id} aria-label={label} data-tooltip={label} disabled={!selected||selected.kind==='audio'||selected.kind==='effect'} onClick={()=>onTransition(id)}><div className="transition-art"><img src={`/artwork/transitions/${id}.svg`} alt="" loading="lazy" decoding="async" draggable={false}/></div><b>{label}</b><small>{id==='dissolve'?'交疊 0.5s':id==='none'?'無淡化':'0.5s'}</small></button>)}</div><p className="field-note">交叉溶解會將兩段畫面安排在不同軌道，重合淡化；精確長度可在動畫面板調整。</p></>}
 {tab==='shapes'&&<><div className="shape-grid"><button onClick={()=>onShape('rectangle')}><Square size={44} strokeWidth={1.3}/><span>圓角矩形</span></button><button onClick={()=>onShape('circle')}><Circle size={44} strokeWidth={1.3}/><span>圓形</span></button></div></>}
 </div><div className="library-bottom"><button onClick={onDemo}><Film size={13}/>開啟示範專案<ArrowUpRight size={12}/></button></div></aside>;
}
