import { desktopClass } from '../platform';
import { useEffect, useState } from 'react';
import { ArrowUpRight, Copy, Film, FolderOpen, FolderPlus, LoaderCircle, Pencil, Plus, RotateCcw, Scissors, Search, Trash2, Upload, X } from 'lucide-react';
import { api } from '../api';
import { newProject, shortTime, type Project } from '../../shared/model';
import type { ProjectSummary } from '../../shared/projects';

type Props={busy:boolean;onOpen:(id:string)=>Promise<void>;onCreate:(p:Project)=>Promise<void>;onStart:()=>void;onOpenFile:()=>void;onDemo:()=>void;onError:(e:unknown)=>void};
export default function ProjectHome({busy,onOpen,onCreate,onStart,onOpenFile,onDemo,onError}:Props){
 const [projects,setProjects]=useState<ProjectSummary[]>([]),[query,setQuery]=useState(''),[trash,setTrash]=useState(false),[loading,setLoading]=useState(true),[rename,setRename]=useState<ProjectSummary>(),[name,setName]=useState(''),[working,setWorking]=useState(false);
 const refresh=async()=>{setLoading(true);try{setProjects(await api(`/api/projects${trash?'?trash=1':''}`));}catch(e){onError(e);}finally{setLoading(false);}};
 useEffect(()=>{void refresh();},[trash]);
 const action=async(id:string,kind:string,body?:unknown)=>{setWorking(true);try{await api(`/api/projects/${id}/${kind}`,{method:'POST',...(body?{body:JSON.stringify(body)}:{})});await refresh();setRename(undefined);}catch(e){onError(e);}finally{setWorking(false);}};
 const create=async()=>{if(busy||working)return;setWorking(true);try{await onCreate(newProject());}catch(e){onError(e);}finally{setWorking(false);}};
 const visible=projects.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));
 return <div className={`project-home ${desktopClass}`}>
  <header className="home-header"><div className="brand"><div className="brand-mark"><Scissors size={22}/></div><span>MyCut<span className="brand-period">.</span></span></div><button className="secondary-button" onClick={onOpenFile} disabled={busy||working}><FolderOpen size={16}/>開啟專案檔</button></header>
  <main className="home-main"><section className="home-hero"><div><h1>我的專案</h1><p>開啟專案，或開始新的剪輯。</p></div><div className="home-hero-actions"><button className="primary-button" disabled={busy||working} onClick={()=>void create()}><Plus size={19}/>建立新專案</button><button className="secondary-button" disabled={busy||working} onClick={onStart} data-tooltip="選取影片、音訊或圖片，建立新專案" aria-label="從影片開始">{busy?<LoaderCircle size={17} className="spin"/>:<Upload size={17}/>}從影片開始</button></div></section>
  <section className="home-projects"><div className="home-projects-heading"><div className="home-tabs"><button className={!trash?'active':''} onClick={()=>setTrash(false)}>最近專案 {trash?'':`(${projects.length})`}</button><button className={trash?'active':''} onClick={()=>setTrash(true)}><Trash2 size={14}/>回收區</button></div><label className="search-box"><Search size={15}/><input aria-label="搜尋專案" placeholder="搜尋專案" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
  {trash&&<p className="home-note">移到回收區的專案可隨時還原，原始素材不會刪除。</p>}
  {loading?<div className="home-empty"><LoaderCircle className="spin" size={24}/><p>正在讀取專案</p></div>:visible.length?<div className="project-grid">{visible.map(p=><article className="project-card" key={p.id}>
   <button className="project-cover" aria-label={trash?p.name:`開啟 ${p.name}`} disabled={busy||working||trash} data-tooltip={trash?p.name:`開啟 ${p.name}`} onClick={()=>void onOpen(p.id)}>{p.thumbnail?<img src={p.thumbnail} alt=""/>:<div className="project-cover-empty"><Film size={35} strokeWidth={1.2}/></div>}<span className="project-duration">{shortTime(p.duration)}</span>{!trash&&<span className="project-open"><ArrowUpRight size={22}/></span>}</button>
   <div className="project-card-info"><button className="project-card-title" disabled={busy||working||trash} onClick={()=>void onOpen(p.id)} data-tooltip={p.name} aria-label={p.name}>{p.name}</button><span>{p.width} × {p.height} · {p.fps} fps · {p.clips} 個片段</span><div className="project-card-bottom"><time>{new Date(p.updatedAt).toLocaleString('zh-TW',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time><div>{trash?<button data-tooltip={`還原 ${p.name}`} aria-label={`還原 ${p.name}`} disabled={working} onClick={()=>void action(p.id,'restore')}><RotateCcw size={15}/></button>:<><button data-tooltip={`重新命名 ${p.name}`} aria-label={`重新命名 ${p.name}`} disabled={working} onClick={()=>{setRename(p);setName(p.name);}}><Pencil size={14}/></button><button data-tooltip={`複製 ${p.name}`} aria-label={`複製 ${p.name}`} disabled={working} onClick={()=>void action(p.id,'duplicate')}><Copy size={14}/></button><button data-tooltip={`移至回收區 ${p.name}`} aria-label={`移至回收區 ${p.name}`} disabled={working} onClick={()=>void action(p.id,'trash')}><Trash2 size={14}/></button></>}</div></div></div>
  </article>)}</div>:<div className="home-empty"><FolderPlus size={32} strokeWidth={1.3}/><h3>{query?'找不到符合的專案':trash?'回收區目前是空的':'你的故事，從這裡開始'}</h3><p>{query?'試試其他名稱。':trash?'移除的專案會暫存在這裡。':'建立新專案，或選取影片開始剪輯。'}</p></div>}
  </section><footer className="home-footer"><span>剪輯專案儲存在本機 · 素材保留於原始位置</span><button onClick={onDemo} disabled={busy||working}>開啟示範專案 <ArrowUpRight size={13}/></button></footer></main>
  {rename&&<div className="modal-backdrop"><form className="home-create-modal" role="dialog" aria-modal="true" aria-label="重新命名專案" onSubmit={e=>{e.preventDefault();void action(rename.id,'rename',{name:name.trim()});}}><div className="modal-header"><h2>重新命名專案</h2><button type="button" data-tooltip="關閉" aria-label="關閉" onClick={()=>setRename(undefined)}><X size={18}/></button></div><label>專案名稱<input autoFocus required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary-button" disabled={working||!name.trim()} type="submit">儲存名稱</button></form></div>}
 </div>;
}
