import { desktopClass, shortcut, platform } from './platform';
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { Scissors, Undo2, Redo2, ChevronDown, ArrowUpRight, Check, Home, LoaderCircle, Keyboard, X, FolderOpen, Plus, Download, Upload, Film, CircleHelp, AlertCircle, CheckCircle2, Sparkles } from 'lucide-react';
import { api, download } from './api';
import { safeFileName } from '../shared/platform';
import { newProject, makeClip, uid, endFrame, splitClip, parseSrt, toSrt, clamp, ProjectSchema, type Project, type Clip, type Media, type FontInfo, type ExportJob, type ExportSettings } from '../shared/model';
import Preview from './components/Preview';
import Timeline from './components/Timeline';
import EditorPanels, { defaultPanelWidths } from './components/EditorPanels';
import Inspector from './components/Inspector';
import LibraryPanel, { LibraryNav, type LibraryTab } from './components/LibraryPanel';
import ExportDialog from './components/ExportDialog';
import ProjectHome from './components/ProjectHome';
import CaptionPanel from './components/CaptionPanel';
import EffectsPanel, { EffectControls } from './components/EffectsPanel';
import { enhancedLrc, validWordTiming } from '../shared/karaoke';
import { expandSelection, duplicateSelection, removeSelection, splitSelection, setSelectionRelation, dissolveClip } from '../shared/editing';
import CaptionBatchEditor from './components/CaptionBatchEditor';
import PortableProgress from './components/PortableProgress';
import EffectInspector from './components/EffectInspector';
import { defaultEffects, effectCatalog, type EffectId } from '../shared/effects';
import { applyCaptions } from '../shared/captions';
import { appendClips, insertTimedClips } from '../shared/placement';
import type { ProjectSummary } from '../shared/projects';
import { defaultFontId, type FontPreferences } from '../shared/fonts';

export default function App(){
 const [view,setView]=useState<'home'|'editor'>('home');const startFromFiles=useRef(false);const returningHome=useRef(false);
 const [project,setProject]=useState<Project>(newProject);const [loaded,setLoaded]=useState(false);const [media,setMedia]=useState<Media[]>([]);const [fonts,setFonts]=useState<FontInfo[]>([]);const [jobs,setJobs]=useState<ExportJob[]>([]);const [projects,setProjects]=useState<ProjectSummary[]>([]);
 const [fontPreferences,setFontPreferences]=useState<FontPreferences>({favoriteFontIds:[]});const [fontSaving,setFontSaving]=useState(false);const fontSave=useRef<Promise<void>|undefined>(undefined);
 const [effectMode,setEffectMode]=useState<'global'|'timed'>('global');
 const [panelWidths,setPanelWidths]=useState(defaultPanelWidths);const [captionMode,setCaptionMode]=useState<'captions'|'lyrics'>('captions');
 const defaultFont=defaultFontId(fonts,fontPreferences.favoriteFontIds);
 const [frame,setFrame]=useState(0);const [playing,setPlaying]=useState(false);const [selection,setSelection]=useState<string[]>([]);const [batchOpen,setBatchOpen]=useState(false);const [tab,setTab]=useState<LibraryTab>('media');const [exportOpen,setExportOpen]=useState(false);const [projectOpen,setProjectOpen]=useState(false);const [helpOpen,setHelpOpen]=useState(false);const [busy,setBusy]=useState(false);const [saveStatus,setSaveStatus]=useState('saved');const [toast,setToast]=useState<{text:string;error:boolean}>();const [recording,setRecording]=useState(false);
 const [historyVersion,setHistoryVersion]=useState(0);const past=useRef<Project[]>([]),future=useRef<Project[]>([]);const latest=useRef(project);latest.current=project;const saveChain=useRef(Promise.resolve());const recorder=useRef<MediaRecorder|null>(null);const uploads=useRef(Promise.resolve());const input=useRef<HTMLInputElement>(null);const projectInput=useRef<HTMLInputElement>(null);const toastTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const selectedIds=useMemo(()=>expandSelection(project,selection),[project.clips,selection]);const selectionSet=useMemo(()=>new Set(selectedIds),[selectedIds]);const selected=selection.filter(id=>selectionSet.has(id)).at(-1)??selectedIds.at(-1);
 const setSelected=useCallback((id?:string)=>setSelection(id?[...expandSelection(latest.current,[id]).filter(other=>other!==id),id]:[]),[]);
 const notify=useCallback((text:string,error=false)=>{setToast({text,error});clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(undefined),error?9000:3500);},[]);
 const fail=useCallback((e:unknown)=>notify(e instanceof Error?e.message:String(e),true),[notify]);
 const setFontFavorite=(id:string,checked:boolean)=>{if(fontSave.current)return;setFontSaving(true);const previous=fontPreferences;const favoriteFontIds=checked?[...fontPreferences.favoriteFontIds,id]:fontPreferences.favoriteFontIds.filter(f=>f!==id);setFontPreferences({favoriteFontIds});fontSave.current=api<FontPreferences>('/api/preferences',{method:'PUT',body:JSON.stringify({favoriteFontIds})}).then(setFontPreferences).catch(e=>{setFontPreferences(previous);fail(new Error(`最愛字型儲存失敗，請重試：${e.message}`));}).finally(()=>{fontSave.current=undefined;setFontSaving(false);});};
 const checkpoint=useCallback(()=>{past.current=[...past.current.slice(-79),latest.current];future.current=[];setHistoryVersion(v=>v+1);},[]);
 const update=useCallback((fn:(p:Project)=>Project,history=true)=>{const before=latest.current;const next=fn(before);if(next===before)return;if(history){past.current=[...past.current.slice(-79),before];future.current=[];setHistoryVersion(v=>v+1);}latest.current=next;setSaveStatus('pending');setProject(next);},[]);
 const undo=useCallback(()=>{const prev=past.current.pop();if(!prev)return;future.current.push(latest.current);latest.current=prev;setSaveStatus('pending');setProject(prev);setHistoryVersion(v=>v+1);},[]);
 const redo=useCallback(()=>{const next=future.current.pop();if(!next)return;past.current.push(latest.current);latest.current=next;setSaveStatus('pending');setProject(next);setHistoryVersion(v=>v+1);},[]);
 const save=useCallback((p:Project)=>{setSaveStatus('saving');const task=saveChain.current.catch(()=>{}).then(async()=>{await api(`/api/projects/${p.id}`,{method:'PUT',body:JSON.stringify(p)});});saveChain.current=task;task.then(()=>{if(latest.current===p)setSaveStatus('saved');},e=>{setSaveStatus('error');fail(e);});return task;},[fail]);
 const loadProject=useCallback((p:Project)=>{startFromFiles.current=false;setView('editor');setPlaying(false);setFrame(0);setSelected(undefined);past.current=[];future.current=[];latest.current=p;setProject(p);setHistoryVersion(v=>v+1);setProjectOpen(false);setBatchOpen(false);},[]);
 const demo=async()=>{try{if(loaded&&view==='editor')await save(latest.current);setBusy(true);const result=await api<{project:Project;media:Media[]}>('/api/demo',{method:'POST'});loadProject(result.project);setMedia(result.media);}catch(e){fail(e);}finally{setBusy(false);}};
 useEffect(()=>{let canceled=false;(async()=>{try{const [fonts,media,projects,jobs,preferences]=await Promise.all([api<FontInfo[]>('/api/fonts'),api<Media[]>('/api/media'),api<ProjectSummary[]>('/api/projects'),api<ExportJob[]>('/api/exports'),api<FontPreferences>('/api/preferences')]);if(canceled)return;setFonts(fonts);setFontPreferences(preferences);setMedia(media);setProjects(projects);setJobs(jobs);if(!canceled)setLoaded(true);}catch(e){if(!canceled){fail(e);setLoaded(true);}}})();return()=>{canceled=true;};},[]);
 useEffect(()=>{const link=document.createElement('link');link.rel='stylesheet';link.href='/fonts/fonts.css';document.head.appendChild(link);return()=>link.remove();},[]);
 useEffect(()=>{if(!loaded||view!=='editor')return;setSaveStatus('pending');const timer=setTimeout(()=>void save(project).catch(()=>{}),700);return()=>clearTimeout(timer);},[project,loaded,save,view]);
 useEffect(()=>{if(!loaded)return;const timer=setInterval(()=>{void api<Media[]>('/api/media').then(setMedia).catch(()=>{});void api<ExportJob[]>('/api/exports').then(setJobs).catch(()=>{});},exportOpen?1000:5000);return()=>clearInterval(timer);},[loaded,exportOpen]);
 useEffect(()=>{const beforeUnload=(e:BeforeUnloadEvent)=>{if(saveStatus==='pending'||saveStatus==='saving'||recording||fontSaving){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',beforeUnload);return()=>window.removeEventListener('beforeunload',beforeUnload);},[saveStatus,recording,fontSaving]);
 const current=project.clips.find(c=>c.id===selected);const locked=project.clips.some(c=>selectionSet.has(c.id)&&project.tracks.find(t=>t.id===c.trackId)?.locked);
 const addMedia=(id:string,track?:string,start?:number)=>{try{const m=media.find(m=>m.id===id);if(!m)return;if(m.missing){notify('素材已移動，請先重新連結。',true);return;}const trackId=track??(m.kind==='audio'?'music':'main');const t=project.tracks.find(t=>t.id===trackId);if(t?.locked){notify('此軌道已鎖定');return;}if((m.kind==='audio')!==(t?.kind==='audio')){notify('請將音訊放到音訊軌，畫面放到影片軌。',true);return;}const at=start??Math.max(0,...project.clips.filter(c=>c.trackId===trackId).map(c=>c.start+c.duration));const c=makeClip({kind:m.kind,mediaId:id,trackId,start:at,duration:Math.max(1,Math.round(m.duration*project.fps)),name:m.name});update(p=>appendClips(p,[c]));setSelected(c.id);setFrame(latest.current.clips.find(x=>x.id===c.id)!.start);}catch(e){fail(e);}};
 const addText=(style='title')=>{try{const subtitle=style==='subtitle';const c=makeClip({kind:'text',trackId:project.tracks.find(t=>t.kind==='text'&&!t.locked)?.id??project.tracks.find(t=>t.kind==='video'&&!t.locked)?.id??project.tracks[0].id,start:frame,duration:3*project.fps,captionType:subtitle?'captions':undefined,name:subtitle?'新增字幕':'新增文字',text:style==='english'?'MAKE IT YOURS.':subtitle?'輸入你的字幕':'讓故事，自由發生。',y:subtitle?.35:0,fontSize:subtitle?56:style==='english'?90:100,fontId:style==='editorial'?'notoseriftc':style==='english'?'montserrat':defaultFont,textBackground:subtitle});if(project.tracks.find(t=>t.id===c.trackId)?.locked){notify('請先解鎖一條文字或影片軌道');return;}update(p=>appendClips(p,[c]));setSelected(c.id);setFrame(latest.current.clips.find(x=>x.id===c.id)!.start);setPlaying(false);}catch(e){fail(e);}};
 const importCaptions=async(f:File)=>{try{const t=project.tracks.find(t=>t.kind==='text'&&!t.locked);if(!t)throw new Error('請先解鎖文字軌');const clips=parseSrt(await f.text(),project.fps,t.id).map(c=>({...c,fontId:defaultFont}));if(!clips.length)throw new Error('找不到有效的 SRT 字幕');update(p=>insertTimedClips(p,clips));notify(`已匯入 ${clips.length} 則字幕`);}catch(e){fail(e);}};
 const exportCaptions=()=>download(`${project.name}.srt`,toSrt(project),'text/plain;charset=utf-8');
 const exportWordLrc=()=>{if(current?.kind==='text'&&validWordTiming(current.text,current.karaoke.words))download(`${current.name}.word.lrc`,enhancedLrc(current.text,current.karaoke.words,project.fps,current.start,current.karaoke.offset),'text/plain;charset=utf-8');};
 const openCaptionBatch=()=>{setPlaying(false);setBatchOpen(true);};
 const effect=(fields:Partial<Clip>)=>{if(!selected||locked)return;update(p=>({...p,clips:p.clips.map(c=>c.id===selected?{...c,...fields}:c)}));};
 const remove=(ripple=false)=>{try{update(p=>removeSelection(p,selectedIds,ripple));setSelected(undefined);}catch(e){fail(e);}};
 const split=()=>{try{const result=splitSelection(project,selectedIds,frame);update(()=>result.project);setSelection(result.ids);}catch(e){fail(e);}};
 const duplicate=()=>{try{const result=duplicateSelection(project,selectedIds);update(()=>result.project);setSelection(result.ids);}catch(e){fail(e);}};
 const relation=(key:'groupId'|'linkId',enabled:boolean)=>{try{update(p=>setSelectionRelation(p,selectedIds,key,enabled));notify(key==='groupId'?(enabled?'已建立群組':'已解除群組'):(enabled?'已連動音訊與影片':'已解除音畫連動'));}catch(e){fail(e);}};
 const addTimedEffect=(id:EffectId)=>{try{let track=project.tracks.find(t=>t.kind==='effect'&&!t.locked);if(!track&&project.tracks.length>=32)throw new Error('最多支援 32 條軌道，請先解鎖特效軌。');track??={id:uid(),kind:'effect',name:'特效',locked:false,hidden:false,muted:false};const c=makeClip({kind:'effect',trackId:track.id,start:frame,duration:project.fps*3,name:effectCatalog.find(e=>e.id===id)!.name,effects:{...defaultEffects(),enabled:[id]}});const target=track;update(p=>appendClips({...p,tracks:p.tracks.some(t=>t.id===target.id)?p.tracks:[target,...p.tracks]},[c]));setSelected(c.id);setFrame(latest.current.clips.find(x=>x.id===c.id)!.start);setPlaying(false);}catch(e){fail(e);}};
 const marker=()=>update(p=>({...p,markers:[...p.markers,{id:uid(),frame,name:`標記 ${p.markers.length+1}`}]}));
 const detach=()=>{if(!current||locked||current.kind!=='video'||!media.find(m=>m.id===current.mediaId)?.hasAudio)return;if(current.linkId){notify('此影片已連動音訊，請先解除連動後再分離。');return;}const t=project.tracks.find(t=>t.kind==='audio'&&!t.locked);if(!t){notify('請先建立或解鎖音訊軌');return;}const linkId=uid();const audio={...current,linkId,id:uid(),kind:'audio' as const,trackId:t.id,name:`${current.name} · 音訊`};try{update(p=>insertTimedClips({...p,clips:p.clips.map(c=>c.id===current.id?{...c,volume:0,linkId}:c)},[audio]));setSelected(audio.id);}catch(e){fail(e);}};
 const transition=(kind:string)=>{if(!current||locked)return;const f=Math.min(Math.round(project.fps*.5),Math.floor(current.duration/2));if(kind==='dissolve'){try{update(p=>dissolveClip(p,current.id));}catch(e){fail(e);}}else effect({fadeIn:kind==='fade'||kind==='in'?f:0,fadeOut:kind==='fade'||kind==='out'?f:0});};
 const createProject=async(p:Project)=>{await save(p);loadProject(p);};
 const startWithMedia=async(list:Media[],ids:string[])=>{if(!ids.length)return;const p=newProject();const first=list.find(m=>m.id===ids[0]);p.name=(first?.name.replace(/\.[^.]+$/,'')||'新影片').slice(0,120);if(first&&first.height>first.width&&first.kind!=='audio'){p.width=1080;p.height=1920;}const ends={main:0,music:0};for(const id of ids){const m=list.find(m=>m.id===id);if(!m)continue;const trackId=m.kind==='audio'?'music':'main';const duration=Math.max(1,Math.round(m.duration*p.fps));p.clips.push(makeClip({kind:m.kind,mediaId:id,trackId,start:ends[trackId],duration,name:m.name}));ends[trackId]+=duration;}await createProject(p);};
 const importFiles=async(files:File[])=>{if(!files.length)return;setBusy(true);const start=startFromFiles.current;startFromFiles.current=false;try{const body=new FormData();files.forEach(f=>body.append('files',f));const result=await api<{media:Media[];errors:string[];imported:string[]}>('/api/media/upload',{method:'POST',body});setMedia(result.media);if(start)await startWithMedia(result.media,result.imported);if(result.errors.length)notify(result.errors.join('；'),true);else notify(`已匯入 ${files.length} 個素材`);}catch(e){fail(e);}finally{setBusy(false);}};
 const pickFiles=async(start=false)=>{startFromFiles.current=start;if(window.mycut){setBusy(true);try{const r=await window.mycut.importFiles();setMedia(r.media);if(start)await startWithMedia(r.media,r.imported);if(r.errors.length)notify(r.errors.join('；'),true);}catch(e){fail(e);}finally{setBusy(false);startFromFiles.current=false;}}else input.current?.click();};
 const openProjectFile=async()=>{if(window.mycut){setBusy(true);try{if(view==='editor')await save(latest.current);const p=await window.mycut.openProject();if(p){setMedia(await api<Media[]>('/api/media'));loadProject(p);}}catch(e){fail(e);}finally{setBusy(false);}}else projectInput.current?.click();};
 const packProject=async()=>{if(!window.mycut)return;setBusy(true);try{const snapshot=latest.current;await save(snapshot);if(await window.mycut.packProject(snapshot))notify('完整專案包已儲存，包含剪輯設定與所有使用的原始素材。');}catch(e){fail(e);}finally{setBusy(false);}};
 const goHome=useCallback(async()=>{if(returningHome.current)return;if(recording){notify('請先停止旁白錄音，再返回首頁。');return;}returningHome.current=true;setPlaying(false);try{let snapshot:Project;await fontSave.current;do{snapshot=latest.current;await save(snapshot);}while(snapshot!==latest.current);setProjectOpen(false);setExportOpen(false);setHelpOpen(false);setBatchOpen(false);setView('home');}catch(e){fail(e);}finally{returningHome.current=false;}},[recording,notify,save,fail]);
 useLayoutEffect(()=>{const desktop=window.mycut;if(!desktop?.onCloseEditor||!desktop.setEditorOpen)return;const unsubscribe=desktop.onCloseEditor(()=>{if(view==='editor')void goHome();});void desktop.setEditorOpen(view==='editor').catch(fail);return unsubscribe;},[view,goHome,fail]);
 const openSaved=async(id:string)=>{setBusy(true);try{loadProject(await api<Project>(`/api/projects/${id}`));}catch(e){fail(e);}finally{setBusy(false);}};
 const record=async()=>{if(recording){recorder.current?.stop();setRecording(false);return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const {id}=await api<{id:string}>('/api/recordings',{method:'POST'});const rec=new MediaRecorder(stream,{mimeType:'audio/webm'});recorder.current=rec;uploads.current=Promise.resolve();let seq=0;let failed=false;rec.ondataavailable=e=>{if(!e.data.size)return;const sequence=seq++;uploads.current=uploads.current.then(async()=>{await api(`/api/recordings/${id}/${sequence}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:e.data});}).catch(e=>{failed=true;fail(e);if(rec.state!=='inactive')rec.stop();});};rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setRecording(false);await uploads.current;if(!failed){try{const m=await api<Media[]>('/api/recordings/'+id+'/finish',{method:'POST'});setMedia(m);notify('旁白已儲存到音訊素材庫');}catch(e){fail(e);}}};rec.start(1000);setRecording(true);}catch(e){fail(e);}};
 const exportMovie=async(settings:ExportSettings)=>{try{await save(project);await api('/api/exports',{method:'POST',body:JSON.stringify({project,settings})});setJobs(await api('/api/exports'));notify('已加入匯出佇列');}catch(e){fail(e);}};
 const saveExport=async(j:ExportJob)=>{try{if(window.mycut)await window.mycut.saveExport(j.id);else{const a=document.createElement('a');a.href=j.output!;a.download=`${safeFileName(j.name)}.mp4`;a.click();}}catch(e){fail(e);}};
 const openProjects=async()=>{try{await save(project);setProjects(await api('/api/projects'));setProjectOpen(true);}catch(e){fail(e);}};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(view!=='editor'||document.querySelector('[role=dialog]'))return;if(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,[contenteditable]'))return;const mod=e.metaKey||e.ctrlKey;if(e.key==='Escape'){setExportOpen(false);setProjectOpen(false);setHelpOpen(false);setSelected(undefined);return;}if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(platform!=='darwin'&&e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}else if(mod&&e.key.toLowerCase()==='a'){e.preventDefault();setSelection(project.clips.filter(c=>!project.tracks.find(t=>t.id===c.trackId)?.locked).map(c=>c.id));}else if(mod&&e.key.toLowerCase()==='g'){e.preventDefault();relation('groupId',!e.shiftKey);}else if(mod&&e.key.toLowerCase()==='b'){e.preventDefault();split();}else if(mod&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate();}else if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();void save(project).catch(()=>{});}else if(mod&&e.key.toLowerCase()==='e'){e.preventDefault();setExportOpen(true);}else if(e.code==='Space'){e.preventDefault();if(project.clips.length){if(frame>=endFrame(project)-1)setFrame(0);setPlaying(v=>!v);}}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove(e.shiftKey);}else if(e.key.toLowerCase()==='m')marker();else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();setPlaying(false);setFrame(f=>clamp(f+(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?project.fps:1),0,endFrame(project)));}else if(e.key==='?')setHelpOpen(true);};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
 const fileInputs=<><input ref={input} type="file" multiple accept="video/*,audio/*,image/*,.mkv,.mov,.flac" hidden onChange={e=>{void importFiles(Array.from(e.target.files??[]));e.target.value='';}}/><input ref={projectInput} type="file" accept=".json,.mycut" hidden onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{const p=ProjectSchema.parse(JSON.parse(await f.text()));if(view==='editor')await save(latest.current);await createProject({...p,id:uid(),name:(p.name+' · 匯入').slice(0,120)});}catch(err){fail(err);}}}/></>;
 const feedback=<><PortableProgress/>{toast&&<div role="status" className={`toast ${toast.error?'error':''}`}>{toast.error?<AlertCircle size={17}/>:<CheckCircle2 size={17}/>}<span>{toast.text}</span><button data-tooltip="關閉提示" aria-label="關閉提示" onClick={()=>setToast(undefined)}><X size={14}/></button></div>}{!loaded&&<div className="loading-screen"><div className="brand-mark"><Scissors size={26}/></div><h2>MyCut.</h2><span><LoaderCircle size={14} className="spin"/> 正在準備你的剪輯空間</span></div>}</>;
 if(view==='home')return <><ProjectHome busy={busy||!loaded} onOpen={openSaved} onCreate={createProject} onStart={()=>void pickFiles(true)} onOpenFile={()=>void openProjectFile()} onDemo={()=>void demo()} onError={fail}/>{fileInputs}{feedback}</>;
 return <div className={`app-shell ${desktopClass}`}><header className="app-header"><div className="brand"><div className="brand-mark"><Scissors size={22} strokeWidth={2}/></div><span>MyCut<span className="brand-period">.</span></span></div><div className="header-divider"/><button className="home-back" aria-label="返回專案首頁" data-tooltip="返回專案首頁" onClick={()=>void goHome()}><Home size={17}/></button><button data-tooltip="專案管理" className="project-switch" onClick={()=>void openProjects()}><FolderOpen size={14}/><span>{project.name}</span><ChevronDown size={13}/></button><span className={`save-state ${saveStatus==='error'?'error':''}`}>{saveStatus==='saving'||saveStatus==='pending'?<LoaderCircle size={12} className="spin"/>:saveStatus==='error'?<AlertCircle size={12}/>:<Check size={12}/>}<span>{saveStatus==='error'?'儲存失敗':saveStatus==='saved'?'已儲存至本機':'儲存中'}</span></span><div className="header-actions"><div className="undo-actions"><button data-tooltip={`復原（${shortcut('Z')}）`} aria-label={`復原（${shortcut('Z')}）`} disabled={!past.current.length} onClick={undo}><Undo2 size={17}/></button><button data-tooltip={`重做（${shortcut('Z',true)}）`} aria-label={`重做（${shortcut('Z',true)}）`} disabled={!future.current.length} onClick={redo}><Redo2 size={17}/></button></div><button className="shortcut-button" data-tooltip="快捷鍵" aria-label="快捷鍵" onClick={()=>setHelpOpen(true)}><Keyboard size={17}/></button><button className="primary-button" onClick={()=>{setPlaying(false);setExportOpen(true);}}>匯出影片<ArrowUpRight size={17}/></button></div></header>
 <EditorPanels widths={panelWidths} onWidths={setPanelWidths} navigation={<LibraryNav tab={tab} setTab={next=>{setTab(next);if(next==='atmosphere'&&effectMode==='global')setSelected(undefined);}}/>} library={<LibraryPanel effectTools={<EffectsPanel value={project.effects??defaultEffects()} mode={effectMode} onMode={mode=>{setEffectMode(mode);if(mode==='global')setSelected(undefined);}} onChange={effects=>{update(p=>({...p,effects}));setSelected(undefined);}} onAdd={addTimedEffect}/>} captionTools={<><button className="wide-button batch-open" onClick={openCaptionBatch}>字幕批次編輯</button><CaptionPanel key={project.id} mode={captionMode} onMode={setCaptionMode} project={project} media={media} selected={current} onApply={(job,cues)=>{update(p=>applyCaptions(p,job,cues,media,defaultFont));notify(`已加入 ${cues.length} 則${job.options.mode==='lyrics'?'歌詞':'字幕'}`);}} onSeek={f=>{setFrame(f);setPlaying(false);}} onError={fail}/></>} tab={tab} media={media} busy={busy} onImport={()=>void pickFiles()} onFiles={files=>void importFiles(files)} onAdd={id=>addMedia(id)} onText={addText} onShape={shape=>{try{const track=project.tracks.find(t=>t.id==='overlay'&&!t.locked)??project.tracks.find(t=>t.kind==='video'&&!t.locked);if(!track){notify('請先解鎖影片軌');return;}const c=makeClip({kind:'shape',trackId:track.id,start:frame,duration:project.fps*3,name:shape==='circle'?'圓形':'圓角矩形',shape,color:'#b8e6bd'});update(p=>appendClips(p,[c]));setSelected(c.id);setFrame(latest.current.clips.find(x=>x.id===c.id)!.start);setPlaying(false);}catch(e){fail(e);}}} onCaptionImport={importCaptions} onCaptionExport={exportCaptions} onWordLrcExport={exportWordLrc} canExportWordLrc={current?.kind==='text'&&validWordTiming(current.text,current.karaoke.words)} onDetach={detach} canDetach={!locked&&current?.kind==='video'&&!!media.find(m=>m.id===current.mediaId)?.hasAudio&&!current.linkId} onEffect={effect} onTransition={transition} onProxy={id=>void api(`/api/media/${id}/proxy`,{method:'POST'}).then(()=>notify('已排入代理檔處理佇列')).catch(fail)} onRelink={id=>{if(window.mycut)void window.mycut.relink(id).then(setMedia).catch(fail);else notify('請從桌面版重新連結素材。');}} onDemo={()=>void demo()} onRecord={()=>void record()} recording={recording} selected={current}/>}
 player={<Preview project={project} media={media} fonts={fonts} frame={frame} playing={playing} setFrame={setFrame} setPlaying={setPlaying} onSelect={setSelected} selected={selected} onError={s=>notify(s,true)}/>} inspector={tab==='atmosphere'&&effectMode==='global'&&!current?<aside className="inspector"><div className="panel-header"><span>全片特效屬性</span><Sparkles size={15}/></div><div className="inspector-scroll"><EffectControls value={project.effects??defaultEffects()} onChange={(effects,history)=>update(p=>({...p,effects}),history)} onCheckpoint={checkpoint}/></div></aside>:current?.kind==='effect'&&!locked?<EffectInspector project={project} media={media} clip={current} frame={frame} update={update} checkpoint={checkpoint} onError={fail} onSeek={setFrame}/>:<Inspector onSelectCaption={c=>{setSelected(c.id);setFrame(c.start);setPlaying(false);}} project={project} clip={locked?undefined:current} media={media} fonts={fonts} fontFavorites={fontPreferences.favoriteFontIds} defaultFontId={defaultFont} fontSaving={fontSaving} onFontFavorite={setFontFavorite} frame={frame} update={update} playing={playing} onSeek={setFrame} onPlaying={setPlaying} onError={fail}/>}/>
 <Timeline project={project} media={media} frame={frame} selected={selected} selectedIds={selectedIds} onSelection={setSelection} onRelation={relation} onError={fail} onSelect={setSelected} setFrame={setFrame} setPlaying={setPlaying} update={update} checkpoint={checkpoint} onSplit={split} onDelete={()=>remove()} onDuplicate={duplicate} onAddMedia={addMedia} onAddTrack={()=>{if(project.tracks.length>=32){notify('最多支援 32 條軌道');return;}const kind=tab==='atmosphere'?'effect':tab==='audio'?'audio':'video';update(p=>({...p,tracks:[{id:uid(),kind,name:`${kind==='effect'?'特效':kind==='audio'?'音訊':'影片'} ${p.tracks.length+1}`,hidden:false,muted:false,locked:false},...p.tracks]}));}} onMarker={marker}/>
 {fileInputs}
 {batchOpen&&<CaptionBatchEditor project={project} selected={selectedIds} fonts={fonts} defaultFontId={defaultFont} onApply={p=>{update(()=>p);notify('字幕批次變更已儲存');}} onClose={()=>setBatchOpen(false)} onSeek={setFrame}/>}
 {exportOpen&&<ExportDialog project={project} jobs={jobs} onClose={()=>setExportOpen(false)} onExport={exportMovie} onPause={id=>void api(`/api/exports/${id}/pause`,{method:'POST'}).then(async()=>setJobs(await api('/api/exports'))).catch(fail)} onResume={id=>void api(`/api/exports/${id}/resume`,{method:'POST'}).then(async()=>setJobs(await api('/api/exports'))).catch(fail)} onSave={j=>void saveExport(j)}/>}
 {projectOpen&&<div className="modal-backdrop" onPointerDown={e=>{if(e.target===e.currentTarget)setProjectOpen(false);}}><section className="project-modal" role="dialog" aria-modal="true" aria-label="專案管理"><div className="modal-header"><div><h2>專案管理</h2></div><button data-tooltip="關閉" aria-label="關閉" onClick={()=>setProjectOpen(false)}><X size={18}/></button></div><label className="project-name-edit">目前專案名稱<input aria-label="專案名稱" value={project.name} maxLength={120} onChange={e=>update(p=>({...p,name:e.target.value||'未命名專案'}))}/></label><div className="project-actions"><button className="primary-button" onClick={async()=>{try{await save(project);loadProject(newProject());}catch(e){fail(e);}}}><Plus size={16}/>新增專案</button><button className="secondary-button" onClick={()=>download(`${safeFileName(project.name)}.mycut.json`,JSON.stringify(project,null,2))}><Download size={15}/>匯出專案 JSON</button><button className="secondary-button" disabled={busy||!window.mycut} onClick={()=>void packProject()}><Download size={15}/>打包完整專案</button><button className="secondary-button" onClick={()=>void openProjectFile()}><Upload size={15}/>匯入專案</button></div><p className="field-note">JSON 只保存剪輯設定；完整專案包（.mycutpack）包含用到的原始素材，可在另一台 Mac／Windows 開啟。打包與還原請使用桌面版。</p><div className="project-list">{projects.map(p=><button key={p.id} onClick={async()=>{try{await save(project);loadProject(await api<Project>(`/api/projects/${p.id}`));}catch(e){fail(e);}}}><Film size={19}/><span><b>{p.name}</b><small>{new Date(p.updatedAt).toLocaleString('zh-TW')}</small></span>{p.id===project.id&&<span className="current-pill">目前</span>}<ArrowUpRight size={15}/></button>)}</div></section></div>}
 {helpOpen&&<div className="modal-backdrop" onPointerDown={e=>{if(e.target===e.currentTarget)setHelpOpen(false);}}><section className="help-modal" role="dialog" aria-modal="true" aria-label="快捷鍵"><div className="modal-header"><h2>快捷鍵</h2><button data-tooltip="關閉" aria-label="關閉" onClick={()=>setHelpOpen(false)}><X size={18}/></button></div><div className="shortcut-list">{[['播放／暫停','Space'],['全選片段',shortcut('A')],['群組 / 解除群組',`${shortcut('G')} / ${shortcut('G',true)}`],['增減選取','Shift 點選 / 框選'],['分割片段',shortcut('B')],['複製片段',shortcut('D')],['刪除片段','Delete'],['漣漪刪除（同軌）','⇧ Delete'],['復原 / 重做',`${shortcut('Z')} / ${shortcut('Z',true)}`],['逐格移動','← / →'],['移動一秒','⇧ ← / →'],['加入標記','M'],['儲存專案',shortcut('S')],['匯出影片',shortcut('E')]].map(([label,key])=><div key={label}><span>{label}</span><kbd>{key}</kbd></div>)}</div><div className="tip"><CircleHelp size={16}/><p>時間軸邊緣可裁切，片段可跨軌拖曳；長影片可先建立代理檔，改善播放效能。</p></div></section></div>}
 {feedback}
 </div>;
}
